#!/bin/sh

# qt-everywhere-opensource-src-4.8.7/src/gui/embedded/qscreenlinuxfb_qws.cpp QLinuxFbScreenPrivate::openTty()
# no blankin' screen, no blinkin' cursor!, no cursor!
echo -e "\033[9;0]\033[?33l\033[?25l\033[?1c" > /dev/tty0

exec /local/root/hmi
