(****************************************************************************
**
** Copyright (C) 2021 Francesco Mandracci
** Contact: https://github.com/fmandracci/smart-home
**
** This file is part of the Smart Home Framework.
**
** Commercial License Usage
** Licensees holding valid commercial licenses may use this file in
** accordance with the terms contained in a written agreement
** between you and the copyright owner.
**
** GNU Lesser General Public License Usage
** Alternatively, this file may be used under the terms of the GNU Lesser
** General Public License version 3 as published by the Free Software
** Foundation and appearing in the file LICENSE included in the
** packaging of this file. Please review the following information to
** ensure the GNU Lesser General Public License version 3 requirements
** will be met: https://www.gnu.org/licenses/lgpl-3.0.html.
**
****************************************************************************)

FUNCTION BA_ClearOKs
#import "Crosstable.gvl"
#import "Resource1.gvl"

    PLC_BA_OK_1  := BA_ClearOK(1 );
    PLC_BA_OK_2  := BA_ClearOK(2 );
    PLC_BA_OK_3  := BA_ClearOK(3 );
    PLC_BA_OK_4  := BA_ClearOK(4 );
    PLC_BA_OK_5  := BA_ClearOK(5 );
    PLC_BA_OK_6  := BA_ClearOK(6 );
    PLC_BA_OK_7  := BA_ClearOK(7 );
    PLC_BA_OK_8  := BA_ClearOK(8 );
    PLC_BA_OK_9  := BA_ClearOK(9 );
    PLC_BA_OK_10 := BA_ClearOK(10);
    PLC_BA_OK_11 := BA_ClearOK(11);
    PLC_BA_OK_12 := BA_ClearOK(12);
    PLC_BA_OK_13 := BA_ClearOK(13);
    PLC_BA_OK_14 := BA_ClearOK(14);
    PLC_BA_OK_15 := BA_ClearOK(15);
    PLC_BA_OK_16 := BA_ClearOK(16);

    PLC_BA_OK_17 := BA_ClearOK(17);
    PLC_BA_OK_18 := BA_ClearOK(18);
    PLC_BA_OK_19 := BA_ClearOK(19);
    PLC_BA_OK_20 := BA_ClearOK(20);
    PLC_BA_OK_21 := BA_ClearOK(21);
    PLC_BA_OK_22 := BA_ClearOK(22);
    PLC_BA_OK_23 := BA_ClearOK(23);
    PLC_BA_OK_24 := BA_ClearOK(24);
    PLC_BA_OK_25 := BA_ClearOK(25);
    PLC_BA_OK_26 := BA_ClearOK(26);
    PLC_BA_OK_27 := BA_ClearOK(27);
    PLC_BA_OK_28 := BA_ClearOK(28);
    PLC_BA_OK_29 := BA_ClearOK(29);
    PLC_BA_OK_30 := BA_ClearOK(30);
    PLC_BA_OK_31 := BA_ClearOK(31);
    PLC_BA_OK_32 := BA_ClearOK(32);

END_FUNCTION
